http:
  port: "8081"

adobe-process-api:  
  http-frequency: "5000"
  content-type: "application/json"
  base-path: "/"
  port: "8091"
  response-timeout: "40000"
  path: "/api"
  connection-idle-timeout: "40000"
  http-reconnection-attempts: "2"
  #Replace with respective application hostname
  host: "mule-worker-adobe-process-api.de-c1.eu1.cloudhub.io"

api:
  id: ""